### ISSUE TITLE
no SQL-file?

### ISSUE THREAD

**Issue by jankube** [champ2959/WO-APP#1]
Hi, wanted to have a look in it, but no file to create database-tables?
Regards, Jan

**Comment by erikgall** [comment]
Jan,

Just saw your comment. Would you still like this?

**Comment by jankube** [comment]
Yes, find that quite interesting, what you've started up. Regards, Jan

Jan Kube per Mobilelefon (Daten auf http://jankube.com/impressum)
Am 02.01.2015 01:08 schrieb "Erik Galloway" notifications@github.com:
